# Site settings
title: Awesome ADHD
tag_text: Awesome ADHD
description: A curated list of ADHD apps, books, ideas and resources across the web! 
baseurl: "/awesome-adhd" 
url: "http://xargsuk.github.io"

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["CODE_OF_CONDUCT.md","LICENCE.md"]
sass:
  style: compressed